# Generated by Django 3.1.1 on 2021-03-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesapayment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='organization_balance',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='type',
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='receipt_no',
            field=models.CharField(default='AAA', max_length=15),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='transaction_date',
            field=models.CharField(default='AAA', max_length=20),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.CharField(default='AAA', max_length=15),
        ),
    ]
