# Generated by Django 3.1.1 on 2021-03-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0002_auto_20210308_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
