# Generated by Django 3.1.1 on 2021-02-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201120_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=5)),
                ('picture', models.ImageField(blank=True, upload_to='topitem/%Y/%m/%d')),
            ],
        ),
    ]
