# Generated by Django 3.1.1 on 2021-03-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packaged',
            field=models.BooleanField(default=False),
        ),
    ]
