# Generated by Django 3.1.1 on 2021-03-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_packaged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.CharField(default='V.M', help_text='e.g V.M,Muranga Town', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_point',
            field=models.CharField(default='Manyota', help_text='Building or hostel', max_length=250),
        ),
    ]
